**Import Library**

In [1]:
import pandas as pd
import numpy as np

**Upload** **File**

In [2]:
# from google.colab import files
# uploades = files.upload()

Saving paketdata_mentah.csv to paketdata_mentah.csv

**Mengolah data ke Dataframe atau Pandas**

In [2]:
df_data = pd.read_csv("paket_data.csv", encoding = 'unicode_escape')
df_data.head(10)

,No,Operator,Name,Description,Normal Price,Price,Discount
0,1,XL,"Xtra Hotrod Special 2GB, 7hr",Kuota Utama 500MB + Kuota Area hingga 3.5GB + ...,12000,11200,800
1,2,XL,"Xtra Hotrod Special 3GB, 7hr",Kuota Utama 1GB + Kuota Area hingga 6GB + YouT...,15000,14000,1000
2,3,Axis,BRONET Mini 1.5GB 7 hari,Kuota Internet 1.5GB berlaku di semua Jaringan...,14850,13973,877
3,4,Telkomsel,"Telkomsel Data Flash 1GB, 30Hr","Kuota utama 1GB, masa aktif 30 Hari",24280,23550,730
4,5,Axis,BRONET Mini 2GB 7 hari,Kuota Internet 2GB berlaku di semua Jaringan 2...,18849,16357,2492
5,6,XL,"Xtra Hotrod Special 4.5GB, 7hr",Kuota Utama 1.5GB + Kuota Area hingga 8.5GB + ...,20000,18725,1275
6,7,Axis,AIGO Bronet Mini 3GB 15hr,"Kuota Utama 3GB, Kuota Lokal mulai 2GB dan Bon...",22900,21050,1850
7,8,Axis,Paket Internet Axis BRONET 2GB 60 Hari,Kuota 2GB (2G/3G/4G) 24Jam. Masa aktif 60 hari.,29400,26875,2525
8,9,Axis,BRONET Mini 5GB 7 hari,Kuota Internet 5GB berlaku di semua Jaringan 2...,29900,26300,3600
9,10,Axis,BRONET Mini 8GB 7 hari,Kuota Internet 8GB berlaku di semua Jaringan 2...,34900,32450,2450

In [3]:
df_data['Name'] = df_data['Name'].str.lower()
df_data['Description'] = df_data['Description'].str.lower()
df_data['Operator'] = df_data['Operator'].str.lower()

In [4]:
df_data.head(5)

,No,Operator,Name,Description,Normal Price,Price,Discount
0,1,xl,"xtra hotrod special 2gb, 7hr",kuota utama 500mb + kuota area hingga 3.5gb + ...,12000,11200,800
1,2,xl,"xtra hotrod special 3gb, 7hr",kuota utama 1gb + kuota area hingga 6gb + yout...,15000,14000,1000
2,3,axis,bronet mini 1.5gb 7 hari,kuota internet 1.5gb berlaku di semua jaringan...,14850,13973,877
3,4,telkomsel,"telkomsel data flash 1gb, 30hr","kuota utama 1gb, masa aktif 30 hari",24280,23550,730
4,5,axis,bronet mini 2gb 7 hari,kuota internet 2gb berlaku di semua jaringan 2...,18849,16357,2492

In [5]:
name = []
kuota = []
durasi = []

In [6]:
x = 0
for i in range(len(df_data['Name'])):
  data = df_data['Name'][i].replace(',','')
  data = data.replace(' gb','gb')
  data = data.replace(' mb','mb')
  data = data.replace(' hari','hr')
  data = data.replace('hari','hr')
  data = data.replace('/',' ')
  split_data = data.split()
  found = 0
  for j in range(len(split_data)):
    if 'gb' in split_data[j]:
      x+=1
      nama_paket = split_data[:j]
      listToStr = ' '.join(str(elem) for elem in nama_paket)
      name.append(listToStr)
      kuota.append(split_data[j])
      if 'hr' in split_data[len(split_data)-1]:
        durasi.append(split_data[len(split_data)-1])
      elif 'bulan' in split_data[len(split_data)-1]:
        time = split_data[len(split_data)-2]*30
        durasi.append(time)
      else:
        durasi.append("0")
      found = 1
      break
    elif split_data[j][-2:] == 'mb':
      x+=1
      nama_paket = split_data[:j]
      listToStr = ' '.join(str(elem) for elem in nama_paket)
      name.append(listToStr)
      kuota.append(split_data[j])
      if 'hr' in split_data[len(split_data)-1]:
        durasi.append(split_data[len(split_data)-1])
      elif 'bulan' in split_data[len(split_data)-1]:
        time = split_data[len(split_data)-2]*30
        durasi.append(time)
      else:
        durasi.append('0')
      found = 1
      break

  if found == 0:
    kuota.append('')
    if 'hr' in split_data[len(split_data)-1]:
      nama_paket = split_data[:len(split_data)-1]
      listToStr = ' '.join(str(elem) for elem in nama_paket)
      name.append(listToStr)
      durasi.append(split_data[len(split_data)-1])
    elif 'bulan' in split_data[len(split_data)-1]:
      nama_paket = split_data[:len(split_data)-1]
      listToStr = ' '.join(str(elem) for elem in nama_paket)
      name.append(listToStr)
      time = split_data[len(split_data)-2]*30
      durasi.append(time)
    else:
      name.append(data)
      durasi.append('0')
    x+=1
print(x)

233

In [7]:
df_data[20:30]

,No,Operator,Name,Description,Normal Price,Price,Discount
20,21,indosat,freedom internet 44gb / 30 hari + bonus kuota ...,"â¢ kuota utama 44gb, masa aktif 30 hari â¢ b...",109750,104500,5250
21,22,xl,xtra combo flex ultra 35gb + kuota area hingga...,35gb kuota utama + kuota area hingga 40gb + 40...,135000,120150,14850
22,23,xl,xtra combo flex supreme 48gb + kuota area hing...,48gb kuota utama + kuota area hingga 67gb + 60...,185000,164650,20350
23,24,xl,"xtra edukasi 2gb, 1hr","kuota utama 2gb, dapat digunakan di jaringan 2...",1938,1938,62
24,25,xl,"xtra edukasi 5gb, 3hr","kuota utama 5gb, dapat digunakan di jaringan 2...",3435,3435,65
25,26,axis,bronet 24 jam 1gb 1 hr + bonus lokal kuota,main kuota 1gb 1 hari selama 24jam di semua j...,3850,3850,0
26,27,xl,"paket blue 1gb, 2hr",kuota utama 1 gb masa aktif 2 hari,4900,4900,0
27,28,xl,xl pure 500mb 30 hari,"internet 500mb, masa aktif 30 hari.",9250,9250,0
28,29,telkomsel,paket bicara telkomsel 5.000,80 menit onnet + 20 menit all operator. masa a...,7750,7750,0
29,30,xl,"xtra edukasi 15gb, 7hr","kuota utama 15gb, dapat digunakan di jaringan ...",8300,8300,700

In [8]:
df_data['Kuota'] = kuota
df_data['Durasi'] = durasi
df_data['Name'] = name

In [9]:
df_data[1:10]

,No,Operator,Name,Description,Normal Price,Price,Discount,Kuota,Durasi
1,2,xl,xtra hotrod special,kuota utama 1gb + kuota area hingga 6gb + yout...,15000,14000,1000,3gb,7hr
2,3,axis,bronet mini,kuota internet 1.5gb berlaku di semua jaringan...,14850,13973,877,1.5gb,7hr
3,4,telkomsel,telkomsel data flash,"kuota utama 1gb, masa aktif 30 hari",24280,23550,730,1gb,30hr
4,5,axis,bronet mini,kuota internet 2gb berlaku di semua jaringan 2...,18849,16357,2492,2gb,7hr
5,6,xl,xtra hotrod special,kuota utama 1.5gb + kuota area hingga 8.5gb + ...,20000,18725,1275,4.5gb,7hr
6,7,axis,aigo bronet mini,"kuota utama 3gb, kuota lokal mulai 2gb dan bon...",22900,21050,1850,3gb,15hr
7,8,axis,paket internet axis bronet,kuota 2gb (2g/3g/4g) 24jam. masa aktif 60 hari.,29400,26875,2525,2gb,60hr
8,9,axis,bronet mini,kuota internet 5gb berlaku di semua jaringan 2...,29900,26300,3600,5gb,7hr
9,10,axis,bronet mini,kuota internet 8gb berlaku di semua jaringan 2...,34900,32450,2450,8gb,7hr

In [10]:
df_data['Durasi'] = df_data['Durasi'].map(lambda x: x.replace('hr',''))

In [11]:
df = df_data
df.head(5)

,No,Operator,Name,Description,Normal Price,Price,Discount,Kuota,Durasi
0,1,xl,xtra hotrod special,kuota utama 500mb + kuota area hingga 3.5gb + ...,12000,11200,800,2gb,7
1,2,xl,xtra hotrod special,kuota utama 1gb + kuota area hingga 6gb + yout...,15000,14000,1000,3gb,7
2,3,axis,bronet mini,kuota internet 1.5gb berlaku di semua jaringan...,14850,13973,877,1.5gb,7
3,4,telkomsel,telkomsel data flash,"kuota utama 1gb, masa aktif 30 hari",24280,23550,730,1gb,30
4,5,axis,bronet mini,kuota internet 2gb berlaku di semua jaringan 2...,18849,16357,2492,2gb,7

In [ ]:
# df['Kuota'] = df['Kuota'].map(lambda x: x.replace('gb',''))

In [ ]:
# df['Kuota'] = df['Kuota'].map(lambda x: x.replace('mb',''))

In [12]:
df.head(10)

,No,Operator,Name,Description,Normal Price,Price,Discount,Kuota,Durasi
0,1,xl,xtra hotrod special,kuota utama 500mb + kuota area hingga 3.5gb + ...,12000,11200,800,2gb,7
1,2,xl,xtra hotrod special,kuota utama 1gb + kuota area hingga 6gb + yout...,15000,14000,1000,3gb,7
2,3,axis,bronet mini,kuota internet 1.5gb berlaku di semua jaringan...,14850,13973,877,1.5gb,7
3,4,telkomsel,telkomsel data flash,"kuota utama 1gb, masa aktif 30 hari",24280,23550,730,1gb,30
4,5,axis,bronet mini,kuota internet 2gb berlaku di semua jaringan 2...,18849,16357,2492,2gb,7
5,6,xl,xtra hotrod special,kuota utama 1.5gb + kuota area hingga 8.5gb + ...,20000,18725,1275,4.5gb,7
6,7,axis,aigo bronet mini,"kuota utama 3gb, kuota lokal mulai 2gb dan bon...",22900,21050,1850,3gb,15
7,8,axis,paket internet axis bronet,kuota 2gb (2g/3g/4g) 24jam. masa aktif 60 hari.,29400,26875,2525,2gb,60
8,9,axis,bronet mini,kuota internet 5gb berlaku di semua jaringan 2...,29900,26300,3600,5gb,7
9,10,axis,bronet mini,kuota internet 8gb berlaku di semua jaringan 2...,34900,32450,2450,8gb,7

In [13]:
df['Kuota'] = df['Kuota'].astype('string')
df['Operator'] = df['Operator'].astype('string')
df['Name'] = df['Name'].astype('string')
df['Description'] = df['Description'].astype('string')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   No            233 non-null    int64
 1   Operator      233 non-null    string
 2   Name          233 non-null    string
 3   Description   233 non-null    string
 4   Normal Price  233 non-null    int64
 5   Price         233 non-null    int64
 6   Discount      233 non-null    int64
 7   Kuota         233 non-null    string
 8   Durasi        233 non-null    object
dtypes: int64(4), object(1), string(4)
memory usage: 16.5+ KB
None

In [14]:
df

,No,Operator,Name,Description,Normal Price,Price,Discount,Kuota,Durasi
0,1,xl,xtra hotrod special,kuota utama 500mb + kuota area hingga 3.5gb + ...,12000,11200,800,2gb,7
1,2,xl,xtra hotrod special,kuota utama 1gb + kuota area hingga 6gb + yout...,15000,14000,1000,3gb,7
2,3,axis,bronet mini,kuota internet 1.5gb berlaku di semua jaringan...,14850,13973,877,1.5gb,7
3,4,telkomsel,telkomsel data flash,"kuota utama 1gb, masa aktif 30 hari",24280,23550,730,1gb,30
4,5,axis,bronet mini,kuota internet 2gb berlaku di semua jaringan 2...,18849,16357,2492,2gb,7
...,...,...,...,...,...,...,...,...,...
228,229,indosat,freedom combo,â¢ kuota utama 45gb+kuota malam 15gb. â¢ bar...,162600,162600,0,60gb,30
229,230,xl,paket internet xl hotrod,kuota utama 12gb (2g/3g/4g). masa aktif 30 hari.,175895,175895,4105,12gb,0
230,231,telkomsel,paket internet bulanan omg! 210k,kuota 43gb sd 83gb + 2gb omg!,217025,217025,0,,0
231,232,xl,paket internet xl hotrod,kuota utama 16gb (2g/3g/4g). masa aktif 30 hari.,215000,215000,5000,16gb,0
232,233,xl,paket akrab,160gb kuota bersama + bonus kuota pribadi hing...,515000,515000,0,460gb,0

In [15]:
df.loc[df['Durasi'] == '', 'Durasi'] = 0.0

df['Durasi']=df['Durasi'].astype(float)

In [16]:
df.dtypes

No                int64
Operator         string
Name             string
Description      string
Normal Price      int64
Price             int64
Discount          int64
Kuota            string
Durasi          float64
dtype: object

In [17]:
df.head(5)

,No,Operator,Name,Description,Normal Price,Price,Discount,Kuota,Durasi
0,1,xl,xtra hotrod special,kuota utama 500mb + kuota area hingga 3.5gb + ...,12000,11200,800,2gb,7.0
1,2,xl,xtra hotrod special,kuota utama 1gb + kuota area hingga 6gb + yout...,15000,14000,1000,3gb,7.0
2,3,axis,bronet mini,kuota internet 1.5gb berlaku di semua jaringan...,14850,13973,877,1.5gb,7.0
3,4,telkomsel,telkomsel data flash,"kuota utama 1gb, masa aktif 30 hari",24280,23550,730,1gb,30.0
4,5,axis,bronet mini,kuota internet 2gb berlaku di semua jaringan 2...,18849,16357,2492,2gb,7.0

In [18]:
df.to_csv(r'hasil_paketdata.csv', index=False)